version: '3.4'

services:
  recipebook.api:
    image: ${DOCKER_REGISTRY-}recipebookapi
    build:
      context: .
      dockerfile: RecipeBook.Api/Dockerfile
    ports:
        - 5400:8080
        - 5401:8081
